env:
  browser: true
  es6: true

globals:
  cc: true,

extends:
  - 'eslint:recommended'
  - 'eslint-config-airbnb'

parserOptions:
  sourceType: module

rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  strict: 0
  no-console: 0
  no-unused-expressions: 0
  no-underscore-dangle: 0